### ISSUE TITLE
Find engish info

### ISSUE THREAD

**Issue by EldRoos** [GitHub-TC/EmpyrionScripting#13]
**Is your feature request related to a problem? Please describe.**
Takes time to find english version of the readme.

**Describe the solution you'd like**
Add a link to the engish version in the top of the readme:
https://github.com/GitHub-TC/EmpyrionScripting#empyrion-scripting-1

**Describe alternatives you've considered**
Alternatively move english up before german. But then you want a link to the german part.

**Additional context**
--

**Comment by GitHub-TC** [comment]
Done
