### ISSUE TITLE
attempting to access a field {{E.S.Players.[0].DrivingEntity.Name}} results in an error

### ISSUE THREAD

**Issue by drabont7** [GitHub-TC/EmpyrionScripting#14]
**code:**
{{#test E.S.Players.length 'ge' 0}}
{{#if E.S.Players.[0].DrivingEntity}}
{{E.S.Players.[0].DrivingEntity.Name}}
{{/if}}
{{/test}}

**output:**
"{test} [1 ge 0 ]:Exception has been thrown by the target of an invocation. 13:23:50"

**versions:**
Empyrion 1.8.3 3849 04-10:26 
EmpyrionScripting by ASTIC/TC Version:11.0.0.0

**Comment by GitHub-TC** [comment]
Fixed with the 11.1.5
