### ISSUE TITLE
Dismantling Script

### ISSUE THREAD

**Issue by reserect** [GitHub-TC/EmpyrionScripting#15]
**Is your feature request related to a problem? Please describe.**
can not stop players dismantling off bases.

**Describe the solution you'd like**
need to stop certan items from getting dismantled off bases.
mainly alienblocks

**Comment by GitHub-TC** [comment]
You can configure this in the '[SaveGame]\Mods\EmpyrionScripting\Configuration.json' with the section
`DeconstructBlockSubstitution`
