### ISSUE TITLE
Please provide a way to reload the scripting engine.

### ISSUE THREAD

**Issue by etmoonshade** [GitHub-TC/EmpyrionScripting#16]
**Is your feature request related to a problem? Please describe.**
I play exclusively on single player, and a long-standing bug I've noted is that scripting seems to break on a ship when you change playfields. It just entirely stops working - LCDs don't update, etc.

Restarting the game will reliably get scripts working again, at least until you change playfields.

I've also noticed that moving out of range of the ship and coming back (e.g. ~12km on a large planet, or leaving/re-entering a playfield that the ship was already on) will sometimes fix the scripting.

I was told at some point that running a dedicated server on my local computer would allow the scripting engine to continue running in the above circumstances - this really isn't a great solution for me. :)

**Describe the solution you'd like**
I'd like a way to force a reload of the scripting engine via console command or perhaps key combination - anything to avoid having to stop/restart the game.

**Describe alternatives you've considered**
Existing workarounds I know of are listed above. The stop/restart isn't really great when you're in the middle of a fight or jumping into a hostile system or something. Or even when you need to do it more than once or twice in a play session.

**Additional context**
n/a

**Comment by GitHub-TC** [comment]
Unfortunately, this is a bug in Empyrion. I have already reported this to Eleon but I don't know when they will fix it. Until then, the only way to work around the bug is to leave and re-enter the field with another ship. Because only the ship that flies as a pilot is affected.

**Comment by etmoonshade** [comment]
Sad but understood. Thanks for the reply and more detailed explanation.
