### ISSUE TITLE
items tag does not function on unnamed containers

### ISSUE THREAD

**Issue by antihax** [GitHub-TC/EmpyrionScripting#20]
**Describe the bug**
`{{#items @root.E.S "*"}}` ignores containers that have not been named.

**To Reproduce**
Create a ship with two containers and script: 
```
{{#items @root.E.S "*"}}
{{Name}}
{{/items}}
```
Rename one container. Move items between the named and default name container. Observe failure to list items from default named container.

**Expected behavior**
Script should fire on all containers regardless.

**Comment by GitHub-TC** [comment]
Unnamed containers cannot be reached "reasonably" via API and are therefore not supported
