### ISSUE TITLE
Harvest System

### ISSUE THREAD

**Issue by nonsai** [GitHub-TC/EmpyrionScripting#23]
Hey mir gefällt das Harvest System aber ich hab eine frage ist es möglich den Preis für die arbeit an zu passen?

ich hab ein großes schiff wo es läuft aber das kostet 14400 pro ernte. finde ich einwenig viel

**Comment by GitHub-TC** [comment]
In der Konfiguration vom EmpyrionScripting im Savegame
![image](https://user-images.githubusercontent.com/18748431/211264412-0525cd52-6314-456b-9689-bedc214e9a69.png)
