### ISSUE TITLE
Recycle says it takes 4 arguments, but refuses to function with more than 3.

### ISSUE THREAD

**Issue by antihax** [GitHub-TC/EmpyrionScripting#24]
https://github.com/GitHub-TC/EmpyrionScripting/blob/46669e6d8d8c19a36887eeb8da6936b54e045225/EmpyrionScripting/CustomHelpers/ConveyorHelpers.cs#L897

The logic to handle a list of items to recycle does not appear to be written in.

**Comment by GitHub-TC** [comment]
Fixed with 11.1.17
