### ISSUE TITLE
Weird issue 

### ISSUE THREAD

**Issue by reserect** [GitHub-TC/EmpyrionScripting#29]
I have 3 players on the server. 2 saying scripts don't work until the 3rd person is around not sure what is happening but the other 2 says the scripts go off once this other person leaves the server and they can not for the life of them get them started again without the other on. Would there be a reason for this. I just can not seem to figure it out they do not have special privelages all 3 are listed as just players.

**Comment by GitHub-TC** [comment]
You need to turn on the EAC and install the EmpyrionScripting mod on the server. Probably the third player has it running on his client, which is not advisable.
