### ISSUE TITLE
Probleme mit dem alten Server

### ISSUE THREAD

**Issue by Bloodfire2k** [GitHub-TC/EmpyrionScripting#30]
Hi, ich habe ein Problem.
Wir haben 2021 einen Server aufgesetzt. Wir wollten wieder spielen und ich habe das Scripting damals installiert. Meine Basis läuft komplett darüber. Ich habe nun die neuesten scripting Dateien installiert, wenn ich allerdings auf dem Server ankomme und er Treibstoff nachfüllt geht die Verbindung zum Server verloren. Muss ich hier irgendwo etwas anpassen oder warum schmeißt er mich raus? 

Gruß Andy

**Comment by GitHub-TC** [comment]
Es darf NUR auf dem Server installiert sein. Mit der 1.9.12 hat Eleon den Bug eingebaut das die lokalen Mods auch geladen werden und dann zu Fehlern führen, wenn sie das Setting nicht selber erkennen. Du solltest also deine lokale Scripting Mod löschen oder aktualisieren (wobei löschen die bessere Variante ist wenn du auf einem Server spielst)

**Comment by Bloodfire2k** [comment]
Also ich hab beide aktualisiert. Single Player und Multiplayer ich lösch dann mal die Singleplayer Mod und teste es.
