### ISSUE TITLE
Import/Execute From LCD

### ISSUE THREAD

**Issue by shiribailem** [GitHub-TC/EmpyrionScripting#32]
Two of the big limiting factors is the tight character limit and the inability to write custom functions, as well as trying to share data between scripts.

My request would be an import or execute command that allows you to reference the code in another LCD readily, notably sharing the same data variables.

Some handy use cases might be routinely referenced blocks of code, or shipwide variables (though I know json can accomplish this bit, it would still be nicer imo)

**Comment by GitHub-TC** [comment]
Eleon wants to include a "computer block" in one of the next versions with a better editor field and with a capacity of 100k characters - I'm waiting for that ;-)
