### ISSUE TITLE
Improvised Basic Constructing Idea

### ISSUE THREAD

**Issue by shiribailem** [GitHub-TC/EmpyrionScripting#33]
As I understand it the mod api doesn't let you control constructors, but it looks like it has enough to essentially imitate them. The only thing I don't know if it has is the ability to read and utilize the crafting times.

My suggestion for how we might work around this:

* require an npc block, similar to the gardener (call them an engineer in this case)
* reference a constructor (if you can't determine the type needed, just go for advanced constructor)
* to avoid completely bypassing the tech tree, craft by referencing an existing copy rather than an id (you need at least one to be able to craft it)
* if crafting times can't be read, then assume a longer time and call it a cost of automating it

**Comment by GitHub-TC** [comment]
Eleon wants to include API control of the constructors in one of the next versions - I'm waiting for that ;-)
