### ISSUE TITLE
Flag to Deconstruct Cores As Well

### ISSUE THREAD

**Issue by shiribailem** [GitHub-TC/EmpyrionScripting#34]
I don't know if this is entirely possible with the modapi, but it would be really nice to have an option in deconstruct and/or recycle to also remove the core (or a similar command purely for removing the core).

Biggest use case for this is being able to automatically core a ship (I dream of making a shop selling ships and this would let me automatically pop the core so a "buyer" could place their own core)

**Comment by GitHub-TC** [comment]
Since I delete the blocks by "only" setting them to ID 0, I don't want to do this with the core, since I suspect that the game still has to perform special actions here. Therefore, the core must be removed by hand so that the game can process this action completely.
