### ISSUE TITLE
add comments

### ISSUE THREAD

**Issue by mjkatgithub** [GitHub-TC/EmpyrionScripting#35]
It would be great if you could also write comments in your scripts that are not interpreted.

**Is your feature request related to a problem? Please describe.**
Especially when you have many and/or complex scripts, it is difficult to quickly grasp what they are doing.

**Describe the solution you'd like**
it would be very helpful if e.g. every line that begins with `//` is simply ignored not only during "execution" but also in the output on the output LCD

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~
idk yet

**Additional context**
~~Add any other context or screenshots about the feature request here.~~
idk yet

**Comment by GitHub-TC** [comment]
Maybe some of these works
https://stackoverflow.com/questions/15336142/how-to-use-comments-in-handlebar-templates
