### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Daimonicon** [GitHub-TC/EmpyrionScripting#37]
**Describe the bug**
I keep getting the error listed below. Apparently the scripts work most of the time except for the teleport script (forum) which occasionally fails until you restart the game.

**To Reproduce**
I didn't even notice the error for a while. Therefore all I can say is to reproduce and start the game

**Expected behavior**

**Screenshots**
`30-20:46:08.908 21_46 -ERR- {EmpyrionScripting} CurrentDomain_AssemblyResolve: (E:\Spiele\Steam\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Content\Mods\EmpyrionScripting\Assembly-CSharp.XmlSerializers.dll) Unity Root Domain:Assembly-CSharp.XmlSerializers, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null for  -> System.IO.FileNotFoundException: Could not load file or assembly 'E:\Spiele\Steam\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Content\Mods\EmpyrionScripting\Assembly-CSharp.XmlSerializers.dll' or one of its dependencies.
File name: 'E:\Spiele\Steam\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Content\Mods\EmpyrionScripting\Assembly-CSharp.XmlSerializers.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool,System.Threading.StackCrawlMark&)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) [0x00002] in <252f5a151e57406087568ebdeb88d5fe>:0 
  at EmpyrionScripting.CsCompiler.CsCompiler.CurrentDomain_AssemblyResolve (System.Object sender, System.ResolveEventArgs args) [0x00052] in <8c580c0b7d5142d4928811d7a553c5dc>:0 
30-20:46:09.192 21_46 -LOG- Local player 76561198058428862/'Daimonicon'
Initializing with custom id: 76561198058428862`

**Desktop (please complete the following information):**
 - OS: Windows 10x64 22H2
 - Browser: Opera
 - Version Empyrion Scripting  Version: 11.4.1

**Additional context**

**Comment by GitHub-TC** [comment]
Unfortunately, some functions do not work in the SP because the API has bugs here. Run a local dedicated server and connect to it.
