### ISSUE TITLE
Update auf Game version 1.11.5

### ISSUE THREAD

**Issue by MrBons4i** [GitHub-TC/EmpyrionScripting#39]
Hallo

Ich finde deine mod echt cool. 

Nur leider funktioniert es bei mir nicht mit der neusten Game version.

**Comment by GitHub-TC** [comment]
Funktioniert auf den Server di ich betreue probemlos - ggf mal die neueste Version probieren und in den logs schauen ob da Fehlerursachen zu finden sind
