### ISSUE TITLE
More a help request than a feature one, how do get the contents of a chest and iterate through the items checking IDs in c# now?

### ISSUE THREAD

**Issue by GamingDaveUk** [GitHub-TC/EmpyrionScripting#42]
I used to use:
`var sItems = root.CsRoot.Items(root.E.S, "A1SortingBox");` to get a lit of items in chest named A1Sorting.

Then i would iterate through the list using:
```
foreach (var item in sItems)
            {
            }
```
and inside that loop i would check each "item"'s ID number against the set lists...
`if (root.CsRoot.Root.PlainIds["Ore"].Contains(item.Key))`

Then if they matched i would move the item stack to a new chest:

`var ore2 = root.CsRoot.Move(item, root.E.S, "*Ore Box*");`

for some reason despite no errors I can not get this to work now.

So how do i get a item list of whats inside a named chest that i can iterate through and compare to the ID numbers in the set lists?

**Comment by GitHub-TC** [comment]
Please ask this question in the forum
https://empyriononline.com/threads/mod-ext-empyrion-scripting-scripts.92458/
unfortunately I can't answer the players' questions about “HOW” to script it - there are too many for that
