### ISSUE TITLE
Nur Admins können das Script nutzen auf einem Server

### ISSUE THREAD

**Issue by dtmaster79** [GitHub-TC/EmpyrionScripting#6]
Hi,

ich weiß grad nicht mehr weiter.. Ich habe das Script auf meinem Server installiert.. Es funktioniert soweit auch. An der Config habe ich nichts geändert..

Leider ist aber das Problem das ich als Admin ohne Probleme das Script nutzen kann.

Mein Mitspieler ist nur Player und er kann es nicht nutzen. ich habe bei ihm auf Steam zugeschaut das er auch alles richtig macht. Das hat er auch aber bei ihm kommt entweder gar keine Ausgabe oder Fehlermeldungen das z.B. irgendwelche format helper dinge nicht gefunden wurden oder so ähnlich.. Habs grad nicht genau im Kopf da er auf einem anderen Planeten ist..

Ich hoffe du verstehst was ich meine..

Gruß

Tino

**Comment by GitHub-TC** [comment]
Hast du einen "echten" dedicated Server oder spielst du im CooP? Im CooP ist wichtig das in der 
\[EGS\]\\Content\\Mods\\EmpyrionScripting\\EmpyrionScripting_Info.yaml die Zeile
```ModTargets: PfServer,Client``` 
in
```ModTargets: PfServer```
geändert wird, da sonst die Mod doppelt läuft.
Auf dem "dedicated" ist es wichtig das die Mod im "Serververzeichnis" installiert ist und nicht im Client (das könnte der Fehler bei dir sein)

Auf einem dedicated Server sollte es keine Probleme geben und auch normale Spieler können Scripte benutzen (bis auf einige Befehle)

**Comment by GitHub-TC** [comment]
Problem ist offenbar bei dtmaster79 gelöst

**Comment by dtmaster79** [comment]
hey sry ja.. bei meinem kumpel sah alles richtig aus.. aber beim genaueren
hinschauen sah ich seinen fehler.. er hatte code aus nem forum kopiert und
er nutzt edge als browser.. und der hat beim kopieren leerzeichen an
einigen stellen hingemacht..

auf jeden fall keine probleme mehr..

danke

ASTIC ***@***.***> schrieb am Fr., 2. Juli 2021, 11:32:
